/*
 * Swagger Ingredients - OpenAPI 3.0
 * Compares 2 ingredient's similarity.
 *
 * OpenAPI spec version: 1.0.11
 * Contact: apiteam@swagger.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.example.ProductComparison.api.model;

import java.util.Objects;
import java.util.Arrays;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
/**
 * EmptyDataResponse
 */


public class EmptyDataResponse {
  private List<Notifications> notifications = null;

  public EmptyDataResponse notifications(List<Notifications> notifications) {
    this.notifications = notifications;
    return this;
  }

  public EmptyDataResponse addNotificationsItem(Notifications notificationsItem) {
    if (this.notifications == null) {
      this.notifications = new ArrayList<Notifications>();
    }
    this.notifications.add(notificationsItem);
    return this;
  }

   /**
   * Get notifications
   * @return notifications
  **/

  public List<Notifications> getNotifications() {
    return notifications;
  }

  public void setNotifications(List<Notifications> notifications) {
    this.notifications = notifications;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    EmptyDataResponse emptyDataResponse = (EmptyDataResponse) o;
    return Objects.equals(this.notifications, emptyDataResponse.notifications);
  }

  @Override
  public int hashCode() {
    return Objects.hash(notifications);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class EmptyDataResponse {\n");
    
    sb.append("    notifications: ").append(toIndentedString(notifications)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
