openai.api.key: ${open_api_key}
#openai:
#  api:
#    key: open_api_key
management.endpoints.web.exposure.include : health

logging:
  level:
    root: INFO
    #root: DEBUG

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/userDB
    username: postgres
    password: Cherryz1!
    driver-class-name: org.postgresql.Driver
    initialization-mode: always
    initialize: true
    schema: classpath:/schema.sql
    continue-on-error: true

  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true
    hibernate:
      ddl-auto: update
