#openai.api.key: ${open_api_key}
openai:
  api:
    key: ${open_api_key}
management.endpoints.web.exposure.include: health

logging:
  level:
    #root: INFO
    root: DEBUG

spring:
  datasource:
    url: jdbc:postgresql://localhost:3000/postgres
    username: postgres
    password: Cherryz1!
    driver-class-name: org.postgresql.Driver

  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true
    hibernate:
      ddl-auto: none
